AWSTemplateFormatVersion: "2010-09-09"
Description: RDS MySQL in private subnets (prod-lean defaults)

Parameters:
  EnvironmentName:
    Type: String

  DBName:
    Type: String
    Default: appdb

  DBUsername:
    Type: String
    Default: dbadmin

  DBPassword:
    Type: String
    NoEcho: true

  DBInstanceClass:
    Type: String
    Default: db.t3.micro

  AllocatedStorage:
    Type: Number
    Default: 20

  MultiAZ:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"

  EngineVersion:
    Type: String
    Default: "8.0.35"

  AllowedClientCidr:
    Type: String
    Description: CIDR allowed to reach DB (use VPC CIDR for app subnets)
    # Default removed; set value at stack creation

Conditions:
  UseMultiAZ: !Equals [!Ref MultiAZ, "true"]

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for RDS
      SubnetIds:
        - !ImportValue
          Fn::Sub: "${EnvironmentName}-PrivateSubnet1Id"
        - !ImportValue
          Fn::Sub: "${EnvironmentName}-PrivateSubnet2Id"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from app subnets/VPC
      VpcId: !ImportValue
        Fn::Sub: "${EnvironmentName}-VPCId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref AllowedClientCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  MySQLDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      Engine: mysql
      EngineVersion: !Ref EngineVersion
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp3
      MultiAZ: !If [UseMultiAZ, true, false]
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: [!Ref DBSecurityGroup]
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "sat:04:00-sat:05:00"
      AutoMinorVersionUpgrade: true

Outputs:
  DBEndpoint:
    Description: MySQL endpoint DNS
    Value: !GetAtt MySQLDB.Endpoint.Address
    Export:
      Name: !Sub "${EnvironmentName}-DBEndpoint"

  DBSecurityGroupId:
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-DBSecurityGroupId"
